version: '3'
services:
  config-server:
    build: ./config-server
    image: barathece91/springboot-microservices-workshop/config-server
    ports:
      - "8888:8888"
  eureka-server:
    build: ./eureka-server
    ports:
      - "8080:8080"
    depends_on:
     - config-server
  eureka-client-app1:
    build: ./eureka-client-app1
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  eureka-client-app2:
    build: ./eureka-client-app1
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka    
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
  zuul-proxy:
    build: ./zuul-proxy
    ports:
      - "8085:8085"
    depends_on: 
      - config-server
      - eureka-server
      - eureka-client-app1
      - eureka-client-app2
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8080/eureka
      ZUUL_ROUTES_CLIENT1_URL: http://eureka-client-app1:8081
      ZUUL_ROUTES_CLIENT2_URL: http://eureka-client-app2:8082
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888


 