server:
  port: 8085

spring:
  application:
    name: eureka-zuul-proxy

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${eureka.service.url}

zuul:
  routes:
    CLIENT1:
      service-id: eureka-client-app1
      path: /app1/*
      strip-prefix: true
    CLIENT2:
      service-id: eureka-client-app2
      path: /app2/*
      strip-prefix: true

      
      
