
server:
  port: 9000

spring:
  application:
    name: eureka-server

management:
  security:
    enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false

