
server:
  port: 8081

management:
 security:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

logging:
  level:
    org.springframework.web: debug
    org.springframework.cloud: debug
    com.netflix: debug